apiVersion: v1
kind: Secret
metadata:
  name: hermes-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- if .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.telegramBotToken }}
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegramBotToken | quote }}
  {{- end }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  GATEWAY_ALLOW_ALL_USERS: {{ .Values.secrets.gatewayAllowAllUsers | quote }}
  HERMES_ALLOW_ROOT_GATEWAY: {{ .Values.secrets.hermesAllowRootGateway | quote }}
